// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'food.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Food _$FoodFromJson(Map<String, dynamic> json) => Food(
  foodCode: json['food_code'] as String,
  foodName: json['food_name'] as String,
  dataTypeCode: json['data_type_code'] as String,
  dataTypeName: json['data_type_name'] as String,
  foodOriginCode: json['food_origin_code'] as String,
  foodOriginName: json['food_origin_name'] as String,
  foodMajorCategoryCode: json['food_major_category_code'] as String,
  foodMajorCategoryName: json['food_major_category_name'] as String,
  representativeFoodCode: json['representative_food_code'] as String,
  representativeFoodName: json['representative_food_name'] as String,
  foodMiddleCategoryCode: json['food_middle_category_code'] as String,
  foodMiddleCategoryName: json['food_middle_category_name'] as String,
  foodSubCategoryCode: json['food_sub_category_code'] as String,
  foodSubCategoryName: json['food_sub_category_name'] as String,
  foodDetailCategoryCode: json['food_detail_category_code'] as String,
  foodDetailCategoryName: json['food_detail_category_name'] as String,
  nutritionReferenceAmount: json['nutrition_reference_amount'] as String,
  energyKcal: (json['energy_kcal'] as num).toDouble(),
  waterG: (json['water_g'] as num).toDouble(),
  proteinG: (json['protein_g'] as num).toDouble(),
  fatG: (json['fat_g'] as num).toDouble(),
  ashG: (json['ash_g'] as num).toDouble(),
  carbohydrateG: (json['carbohydrate_g'] as num).toDouble(),
  sugarsG: (json['sugars_g'] as num).toDouble(),
  dietaryFiberG: (json['dietary_fiber_g'] as num).toDouble(),
  calciumMg: (json['calcium_mg'] as num).toDouble(),
  ironMg: (json['iron_mg'] as num).toDouble(),
  phosphorusMg: (json['phosphorus_mg'] as num).toDouble(),
  potassiumMg: (json['potassium_mg'] as num).toDouble(),
  sodiumMg: (json['sodium_mg'] as num).toDouble(),
  vitaminARae: (json['vitamin_a_μg_rae'] as num).toDouble(),
  retinol: (json['retinol_μg'] as num).toDouble(),
  betaCarotene: (json['beta_carotene_μg'] as num).toDouble(),
  thiaminMg: (json['thiamin_mg'] as num).toDouble(),
  riboflavinMg: (json['riboflavin_mg'] as num).toDouble(),
  niacinMg: (json['niacin_mg'] as num).toDouble(),
  vitaminCMg: (json['vitamin_c_mg'] as num).toDouble(),
  vitaminDMicrog: (json['vitamin_d_μg'] as num).toDouble(),
  cholesterolMg: (json['cholesterol_mg'] as num).toDouble(),
  saturatedFatG: (json['saturated_fat_g'] as num).toDouble(),
  transFatG: (json['trans_fat_g'] as num).toDouble(),
  sourceCode: json['source_code'] as String,
  sourceName: json['source_name'] as String,
  foodWeight: json['food_weight'] as String,
  manufacturer: json['manufacturer'] as String,
  dataCreationMethodCode: json['data_creation_method_code'] as String,
  dataCreationMethodName: json['data_creation_method_name'] as String,
  dataCreationDate: json['data_creation_date'] as String,
  dataReferenceDate: json['data_reference_date'] as String,
);

Map<String, dynamic> _$FoodToJson(Food instance) => <String, dynamic>{
  'food_code': instance.foodCode,
  'food_name': instance.foodName,
  'data_type_code': instance.dataTypeCode,
  'data_type_name': instance.dataTypeName,
  'food_origin_code': instance.foodOriginCode,
  'food_origin_name': instance.foodOriginName,
  'food_major_category_code': instance.foodMajorCategoryCode,
  'food_major_category_name': instance.foodMajorCategoryName,
  'representative_food_code': instance.representativeFoodCode,
  'representative_food_name': instance.representativeFoodName,
  'food_middle_category_code': instance.foodMiddleCategoryCode,
  'food_middle_category_name': instance.foodMiddleCategoryName,
  'food_sub_category_code': instance.foodSubCategoryCode,
  'food_sub_category_name': instance.foodSubCategoryName,
  'food_detail_category_code': instance.foodDetailCategoryCode,
  'food_detail_category_name': instance.foodDetailCategoryName,
  'nutrition_reference_amount': instance.nutritionReferenceAmount,
  'energy_kcal': instance.energyKcal,
  'water_g': instance.waterG,
  'protein_g': instance.proteinG,
  'fat_g': instance.fatG,
  'ash_g': instance.ashG,
  'carbohydrate_g': instance.carbohydrateG,
  'sugars_g': instance.sugarsG,
  'dietary_fiber_g': instance.dietaryFiberG,
  'calcium_mg': instance.calciumMg,
  'iron_mg': instance.ironMg,
  'phosphorus_mg': instance.phosphorusMg,
  'potassium_mg': instance.potassiumMg,
  'sodium_mg': instance.sodiumMg,
  'vitamin_a_μg_rae': instance.vitaminARae,
  'retinol_μg': instance.retinol,
  'beta_carotene_μg': instance.betaCarotene,
  'thiamin_mg': instance.thiaminMg,
  'riboflavin_mg': instance.riboflavinMg,
  'niacin_mg': instance.niacinMg,
  'vitamin_c_mg': instance.vitaminCMg,
  'vitamin_d_μg': instance.vitaminDMicrog,
  'cholesterol_mg': instance.cholesterolMg,
  'saturated_fat_g': instance.saturatedFatG,
  'trans_fat_g': instance.transFatG,
  'source_code': instance.sourceCode,
  'source_name': instance.sourceName,
  'food_weight': instance.foodWeight,
  'manufacturer': instance.manufacturer,
  'data_creation_method_code': instance.dataCreationMethodCode,
  'data_creation_method_name': instance.dataCreationMethodName,
  'data_creation_date': instance.dataCreationDate,
  'data_reference_date': instance.dataReferenceDate,
};
